name: rivabar

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pyqt
  - pandas
  - jupyterlab
  - scipy
  - scikit-image
  - scikit-learn
  - cartopy
  - geopandas
  - pyproj
  - tqdm
  - networkx
  - shapely
  - libpysal
  - momepy
  - geemap
  - geedim
  - osmnx
  - pip
  - pip:
    - sknw
    - rasterio
    - opencv-python
    - matplotlib-scalebar
    - pystac-client